# Importing the configuration and agent logic
from configuration import config              # This loads the configuration settings (like API keys, environment, etc.)
from agents import Agent, Runner              # Imports custom Agent class and Runner logic to run the agent



# Creating a synchronous agent
sync_agent = Agent(
    name="AI Agent",                          # Name of the agent
    instructions="You are a helpful AI agent."  # Instructions (role/behavior) for the agent
)




# Taking input from the user
prompt = input("Ask question : ")                            # Prompts user to type a message or query



# Running the agent synchronously with the given prompt and configuration
response = Runner.run_sync(
    sync_agent,                               # The agent instance to use
    prompt,                                   # The user's input
    run_config=config                         # The configuration settings to control execution
)
# Printing the final response from the agent
print(response.final_output)                  # Displays the output generated by the agent
